theme: jekyll-theme-minimal

title: ICAI Research Group
description: This is the GitHub webpage for the Computational Intelligence and Image Analysis Group of the University of Málaga
logo: /logo-icai.png
